/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class J2C */

#ifndef _Included_J2C
#define _Included_J2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     J2C
 * Method:    write2proc
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_J2C_write2proc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     J2C
 * Method:    writestring
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_J2C_writestring
  (JNIEnv *, jclass, jstring);

/*
 * Class:     J2C
 * Method:    testJstring
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_J2C_testJstring
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
