[package]
name = "elasticsearch-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
select = "0.6.1"
url = "2.5.4"
threadpool = "1.8.1"
indicatif = "0.17.0"
lazy_static = "1.4.0"
