CREATE DATABASE IF NOT EXISTS testdb1;
CREATE TABLE IF NOT EXISTS testtb1(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL DEFAULT 0,
	name CHAR(16) NOT NULL DEFAULT ''
)ENGINE=INNODB CHARSET=UTF8MB4 COLLATE=UTF8MB4_BIN;
