CREATE DATABASE IF NOT EXISTS db1;
CREATE DATABASE IF NOT EXISTS db2;
DROP TABLE  IF EXISTS db1.t1;  -- rename ?
DROP TABLE  IF EXISTS db2.t1;
CREATE TABLE db1.t1(id INT PRIMARY KEY,name VARCHAR(64) NOT NULL DEFAULT '',`c3` DATE DEFAULT NULL);
CREATE TABLE db2.t1(id INT PRIMARY KEY,name VARCHAR(64) NOT NULL DEFAULT '',`c3` VARCHAR(32) NOT NULL DEFAULT '');
INSERT INTO db1.t1 VALUES (2,'name 2','2023-03-30');
INSERT INTO db2.t1 VALUES(2,'name 2,from db2','2023-03-30');
SELECT * FROM db1.t1;
SELECT * FROM db2.t1;
