debug: false
spring:
  profiles:
    active:
      - dev
  application:
    name: demo
  sql:
    init:
      schema-locations: classpath:user_init.sql

  batch:
    jdbc:
      initialize-schema: never
    job:
      name: importUserJob
      enabled: true  # 开启作业执行，默认是true
      restart: false  # 是否允许重启已完成的作业，默认是false
      initializer:
        enabled: true  # 开启作业初始化器，默认是true
      joblauncher:
        fail-on-no-jobs-found: true  # 当找不到作业时是否失败，默认是true
      job-repository:
        table-prefix: BATCH_  # 作业仓库的表前缀，默认是BATCH_
        isolation-level-for-create: DEFAULT  # 创建作业时的事务隔离级别
        transaction-manager: transactionManager  # 事务管理器名称
        data-source: managerDataSource  # 数据源名称
        max-varchar-length: 2500  # 最大VARCHAR长度
        initialize-schema: never  # 初始化模式，有NEVER、ALWAYS、IF_NEEDED可选

  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:5742/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:5742/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    manager:
      jdbc-url: jdbc:mysql://localhost:5742/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mappers/*.xml  # 指定MyBatis mapper XML文件的位置
  type-aliases-package: com.example.demo.model  # 指定别名包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 配置MyBatis日志实现

server:
  servlet:
    context-path: /
  port: 8082
  undertow:
    threads:
      io: 4
      worker: 20
    url-charset: UTF-8

#pagehelper
pagehelper:
  autoDialect: true
  closeConn: true
  #\u6D4B\u8BD5\u5C5E\u6027\u6CE8\u5165
  # hello: \u4F60\u597D
  # nihao: Hello
  offset-as-page-num: true
  count-column: '*'
  async-count: true
  orderBySqlParser: com.example.demo.page.MyOrderBySqlParser
  helper-dialect: mysql

